apiVersion: apps/v1
kind: Deployment
metadata:
  name:  2fhjuyh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: 2fhjuyh
  template:
    metadata:
      labels:
        app: 2fhjuyh
    spec:
      containers:
      - image: okteto.dev/2fhjuyh:latest
        name: 2fhjuyh
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "96d26c61-8101-4229-a3bb-e8490c6e62fd"
        - name: Vless_Path
          value: "/rttyu2"
        - name: Vmess_UUID
          value: "6c89655a-5238-4716-b410-b184419624f9"
        - name: Vmess_Path
          value: "/rtytuy2"
        - name: Share_Path
          value: "/uytdht2"
