apiVersion: v1
kind: Service
metadata:
  name: 2fhjuyh
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "2fhjuyh"
    port: 8080
  selector:
    app: 2fhjuyh
